### ISSUE TITLE
jsx inside function calls

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/builder-boy#60]
`etc(<div></div>)`

**Comment by jimdebeer** [comment]
seems to be unsupported by acorn-jsx

```
    at Parser.pp$4.raise (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$3.parseExprList (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2152:16)
    at Parser.pp$3.parseSubscripts (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/jimdebeer/Desktop/brisky/builder-boy/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1597:21)
```

**Comment by jimdebeer** [comment]
raise this issue with acorn-jsx / make a pr
